export const GET_MATTERS = 'GET_MATTERS';

export const SORT_MATTERS = 'SORT_MATTERS';

export const SEARCH_MATTERS = 'SEARCH_MATTERS';

export const SELECT_MATTER = 'SELECT_MATTER';

export const ADD_TASK = 'ADD_TASK';

export const EDIT_MATTER_TASK = 'EDIT_MATTER_TASK';

export const ADD_NOTE = 'ADD_NOTE';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';

export const SHOW_MATTER_DETAIL = 'SHOW_MATTER_DETAIL';

export const EDIT_MATTER = 'EDIT_MATTER';

export const SET_MATTER_DETAIL = 'SET_MATTER_DETAIL';

export const RESTORE_STATE = 'RESTORE_STATE';

export const UPDATE_MATTER_FILES = 'UPDATE_MATTER_FILES';

export const UPDATE_RELATIVITY_FIELDS = 'UPDATE_RELATIVITY_FIELDS';

export const SET_CURRENT_MATTER_CORRESPONDANCE = 'SET_CURRENT_MATTER_CORRESPONDANCE';

export const GET_UPDATED_CORRESPONDANCE = 'GET_UPDATED_CORRESPONDANCE'

export const RESET_CLIENT_MATTER = 'RESET_CLIENT_MATTER'
