export const UPLOAD_NEW_DOCUMENT_TEMPLATE = 'UPLOAD_NEW_DOCUMENT_TEMPLATE';
export const TEST_DOCUMENT_TEMPLATE = 'TEST_DOCUMENT_TEMPLATE';
export const GET_NEW_DOCUMENT = 'GET_NEW_DOCUMENT';
export const GET_UPDATED_MATTERS = 'GET_UPDATED_MATTERS';
